Remove commercecode as parameter
TransbankDevelopers/transbank-sdk-java-webpay-rest-example pull request #20
Opened 2019-09-16 14:09 UTC by iescaida

Remove commerce code as parameter since is coming in the header, also swapped type for maxAmount from double to String to allow optionality

2019-09-16 16:17 UTC, a1b4 requested changes

2019-09-16 16:17 UTC, a1b4 commented on src/main/java/cl/transbank/webpay/example/controller/patpass/comercio/PatpassComercioController.java
> +        /*String url = "https://www.help.cl/contrata-online/patpassWs/response.php";
can you remove this commented code?

2019-09-16 16:19 UTC, goncafa commented
@iescaida Why did you have to change the maxAmount param to String instead a Double? If the problem that param should be optional you could manage it with the Double wrapper.

2019-09-16 19:54 UTC, iescaida commented on src/main/java/cl/transbank/webpay/example/controller/patpass/comercio/PatpassComercioController.java
> +        /*String url = "https://www.help.cl/contrata-online/patpassWs/response.php";
done

2019-09-16 19:59 UTC, iescaida commented
> @iescaida Why did you have to change the maxAmount param to String instead a Double? If the problem that param should be optional you could manage it with the Double wrapper.

@goncafa 
I was avoiding the hassle of using a wrapper, since they can pass an empty maxAmount and as far as I know it can't be an empty Double right

2019-09-16 20:33 UTC, goncafa commented
> > @iescaida Why did you have to change the maxAmount param to String instead a Double? If the problem that param should be optional you could manage it with the Double wrapper.
> 
> @goncafa
> I was avoiding the hassle of using a wrapper, since they can pass an empty maxAmount and as far as I know it can't be an empty Double right

@iescaida But you can use null instead and you could overload a method in order to support receive the param or not.

2019-09-25 15:00 UTC, goncafa approved these changes

2019-10-01 14:23 UTC, a1b4 approved these changes
nice work 🎉

2019-10-16 13:42 UTC, merged